-- SET MULTI_THREADED 0;
-- SET CACHE_SIZE 8388608;
-- SET LOG 0;
-- SET LOCK_MODE 0;
-- SET UNDO_LOG 0;

-- EVENTS TABLE.
CREATE TABLE IF NOT EXISTS SCHEMAS (
    INTERNALID  BIGINT AUTO_INCREMENT,
    RESOURCE_SCHEMA_NAME VARCHAR(1024) PRIMARY KEY,
    FROM_SCHEMA VARCHAR(1024),
    OWNER VARCHAR(255),
    AUTHOR VARCHAR(255),
    ALLOW_ALL BOOLEAN,
    RESOURCE BINARY LARGE OBJECT
);

CREATE TABLE IF NOT EXISTS  RESOURCES (
  INTERNALID  BIGINT AUTO_INCREMENT,
  RESOURCE_KEY VARCHAR(1024) PRIMARY KEY, 
  NODEADDRESS VARCHAR(1024), 
  RESOURCE_DOMAIN VARCHAR(255),
  RESOURCE_CLASSNAME VARCHAR(255),
  RESOURCE_ATTRIBUTE_SCHEMA_NAME VARCHAR(255),
  STRUCTURE_ID VARCHAR(255),
  INSERTED_ON TIMESTAMP,
  RESOURCE BINARY LARGE OBJECT
 );

-- PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS RESOURCES_IDX_1 ON RESOURCES(NODEADDRESS,RESOURCE_DOMAIN,RESOURCE_CLASSNAME,RESOURCE_ATTRIBUTE_SCHEMA_NAME);
CREATE INDEX IF NOT EXISTS RESOURCES_IDX_2 ON RESOURCES(STRUCTURE_ID);

CREATE TABLE IF NOT EXISTS  CONNECTIONS (
  INTERNALID  BIGINT AUTO_INCREMENT,
  RESOURCE_KEY VARCHAR(1024) PRIMARY KEY, 
  NODEADDRESS VARCHAR(1024), 
  RESOURCE_DOMAIN VARCHAR(255),
  RESOURCE_CLASSNAME VARCHAR(255),
  RESOURCE_ATTRIBUTE_SCHEMA_NAME VARCHAR(255),
  FROM_RESOURCE VARCHAR(255),
  TO_RESOURCE VARCHAR(255),
  INSERTED_ON TIMESTAMP,
  RESOURCE BINARY LARGE OBJECT
 );




CREATE TABLE IF NOT EXISTS  CIRCUITS (
  INTERNALID  BIGINT AUTO_INCREMENT,
  RESOURCE_KEY VARCHAR(1024) PRIMARY KEY, 
  NODEADDRESS VARCHAR(1024), 
  RESOURCE_NAME VARCHAR(1024), 
  RESOURCE_DOMAIN VARCHAR(255),
  RESOURCE_CLASSNAME VARCHAR(255),
  RESOURCE_ATTRIBUTE_SCHEMA_NAME VARCHAR(255),
  A_RESOURCE VARCHAR(255),
  Z_RESOURCE VARCHAR(255),
  INSERTED_ON TIMESTAMP,
  RESOURCE BINARY LARGE OBJECT
 );

CREATE TABLE IF NOT EXISTS  CIRCUIT_PATHS (
  INTERNALID  BIGINT AUTO_INCREMENT,
  RESOURCE_KEY VARCHAR(1024) PRIMARY KEY, 
  RESOURCE BINARY LARGE OBJECT
 );

/**
  *  Representa um circuito que será criado
  */
CREATE TABLE IF NOT EXISTS  SERVICES (
  INTERNALID  BIGINT AUTO_INCREMENT,
  RESOURCE_KEY VARCHAR(1024) PRIMARY KEY, 
  NODEADDRESS VARCHAR(1024),
  RESOURCE_NAME VARCHAR(1024),
  RESOURCE_DOMAIN VARCHAR(255),
  RESOURCE_CLASSNAME VARCHAR(255),
  RESOURCE_ATTRIBUTE_SCHEMA_NAME VARCHAR(255),
  INSERTED_ON TIMESTAMP,
  RESOURCE BINARY LARGE OBJECT
 );

/**
  *  Representa as depedencias do serviço, geralmente circuitos
  */
CREATE TABLE IF NOT EXISTS  SERVICES_DEPENDENCIES (
  INTERNALID  BIGINT AUTO_INCREMENT,
  SERVICE_KEY VARCHAR(1024) PRIMARY KEY, 
  RESOURCE BINARY LARGE OBJECT
 );


/**
  *  Representa os circuitos do serviço
  */
CREATE TABLE IF NOT EXISTS  SERVICES_CIRCUITS (
    INTERNALID  BIGINT AUTO_INCREMENT,
    SERVICE_KEY  VARCHAR(1024),
    CIRCUIT_KEY VARCHAR(1024)
 );



/**
  * Por padrão agora ele vai excluir os dados anteriores evitando conflitos
  */
-- TRUNCATE TABLE RESOURCES;
-- TRUNCATE TABLE CONNECTIONS;
-- TRUNCATE TABLE CIRCUITS;
SET LOCK_TIMEOUT 3600000;
